name: liquidsoft_components
description: A lightweight but complete flutter component package with Cupertino/Material Widgets,Global Error Handling, HTTP Caller, Platform Identification, and much more.
version: 0.8.2
homepage: https://github.com/cwesterhold/liquidsoft_components

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  connectivity: ^3.0.3
  intl: ^0.17.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
