name: liquidsoft_components
description: A complete flutter component package with Cupertino/Material Widget, HTTP Caller, Platform Identification, and much more.
version: 0.0.3
homepage: https://github.com/cwesterhold/liquidsoft_components

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  catcher: ^0.6.5
  connectivity_plus: ^1.0.0
  package_info_plus: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
